import A from '../../../assets/images/capitals/A.png'
import B from '../../../assets/images/capitals/B.png'
import C from '../../../assets/images/capitals/C.png'
import D from '../../../assets/images/capitals/D.png'
import E from '../../../assets/images/capitals/E.png'
import F from '../../../assets/images/capitals/F.png'
import G from '../../../assets/images/capitals/G.png'
import H from '../../../assets/images/capitals/H.png'
import I from '../../../assets/images/capitals/I.png'
import J from '../../../assets/images/capitals/J.png'
import K from '../../../assets/images/capitals/K.png'
import L from '../../../assets/images/capitals/L.png'
import M from '../../../assets/images/capitals/M.png'
import N from '../../../assets/images/capitals/N.png'
import O from '../../../assets/images/capitals/O.png'
import P from '../../../assets/images/capitals/P.png'
import Q from '../../../assets/images/capitals/Q.png'
import R from '../../../assets/images/capitals/R.png'
import S from '../../../assets/images/capitals/S.png'
import T from '../../../assets/images/capitals/T.png'
import U from '../../../assets/images/capitals/U.png'
import V from '../../../assets/images/capitals/V.png'
import W from '../../../assets/images/capitals/W.png'
import X from '../../../assets/images/capitals/X.png'
import Y from '../../../assets/images/capitals/Y.png'
import Z from '../../../assets/images/capitals/Z.png'

export{
    A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z
}